# Setup
title:               Computer Science and Development Blog-ğŸ‘»
tagline:             ''
description:         'Il Young Hwang(í™©ì¼ì˜)<br>ìš°ë¦¬ ê°™ì´ ì†Œí†µí•´ìš”.'
url:                 https://bluedal.github.io
baseurl:             ''
paginate:            20
permalink:           pretty

# About/contact
author:
  name:              Il Young Hwang
  url:               https://www.facebook.com/10hwang
  email:             ilyoung6016@gmail.com

# Gems
plugins:
  - jekyll-polyglot
  - jekyll-paginate
  - jekyll-seo-tag
  
languages: ['ja', 'ko', 'en']
default_lang: 'ko'
exclude_from_localization: ['javascript', 'images', 'css']
parallel_localization: false

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
